// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	models "github.com/nymtech/nym/validator/nym/directory/models"
	mock "github.com/stretchr/testify/mock"
)

// BatchSanitizer is an autogenerated mock type for the BatchSanitizer type
type BatchSanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: input
func (_m *BatchSanitizer) Sanitize(input models.BatchMixStatus) models.BatchMixStatus {
	ret := _m.Called(input)

	var r0 models.BatchMixStatus
	if rf, ok := ret.Get(0).(func(models.BatchMixStatus) models.BatchMixStatus); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(models.BatchMixStatus)
	}

	return r0
}
