// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenericSanitizer is an autogenerated mock type for the GenericSanitizer type
type GenericSanitizer struct {
	mock.Mock
}

// Sanitize provides a mock function with given fields: input
func (_m *GenericSanitizer) Sanitize(input interface{}) {
	_m.Called(input)
}
