definitions:
  models.BatchMixStatus:
    properties:
      status:
        items:
          $ref: '#/definitions/models.MixStatus'
        type: array
    required:
    - status
    type: object
  models.Error:
    properties:
      error:
        type: string
    type: object
  models.MixStatus:
    properties:
      ipVersion:
        type: string
      pubKey:
        type: string
      up:
        type: boolean
    required:
    - ipVersion
    - pubKey
    - up
    type: object
info:
  contact: {}
  description: A node status API that holds uptime information for Nym nodes.
  license:
    name: Apache 2.0
    url: https://github.com/nymtech/node-status-api/license
  termsOfService: http://swagger.io/terms/
  title: Nym Node Status API
  version: 0.10.0
paths:
  /api/mixmining:
    post:
      consumes:
      - application/json
      description: Nym network monitor sends packets through the system and checks if they make it. The network monitor then hits this method to report whether the node was up at a given time.
      operationId: addMixStatus
      parameters:
      - description: object
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.MixStatus'
      produces:
      - application/json
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Lets the network monitor create a new uptime status for a mix
      tags:
      - mixmining
  /api/mixmining/batch:
    post:
      consumes:
      - application/json
      description: Nym network monitor sends packets through the system and checks if they make it. The network monitor then hits this method to report whether nodes were up at a given time.
      operationId: batchCreateMixStatus
      parameters:
      - description: object
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.BatchMixStatus'
      produces:
      - application/json
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Lets the network monitor create a new uptime status for multiple mixes
      tags:
      - mixmining
  /api/mixmining/fullreport:
    get:
      consumes:
      - application/json
      description: Provides summary uptime statistics for last 5 minutes, day, week, and month
      operationId: batchGetMixStatusReport
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Retrieves a summary report of historical mix status
      tags:
      - mixmining
  /api/mixmining/node/{pubkey}/history:
    get:
      consumes:
      - application/json
      description: Lists all mixnode statuses for a given node pubkey
      operationId: listMixStatuses
      parameters:
      - description: Mixnode Pubkey
        in: path
        name: pubkey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MixStatus'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Lists mixnode activity
      tags:
      - mixmining
  /api/mixmining/node/{pubkey}/report:
    get:
      consumes:
      - application/json
      description: Provides summary uptime statistics for last 5 minutes, day, week, and month
      operationId: getMixStatusReport
      parameters:
      - description: Mixnode Pubkey
        in: path
        name: pubkey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Retrieves a summary report of historical mix status
      tags:
      - mixmining
swagger: "2.0"
